name: Pulumi Preview

on:
  push:
    branches: [ 'main' ]

jobs:
  pulumi-preview:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Pulumi up
        run: pulumi up --yes
        working-directory: ./bigbro